spring:
  application:
    name: JobFinder
  config:
    import: classpath:secret.yaml
  datasource:
    username: seeker
    password: ${datasource.password}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jobs
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  ai:
    chat:
      client:
        enabled: true
    openai:
      api-key: ${openai.api-key}
      chat:
        options:
          model: gpt-3.5-turbo-1106
  telegram-bot:
    name: ${telegram-bot.name}
    token: ${telegram-bot.token}
    creatorId: ${telegram-bot.creatorId}