spring:
  application:
    name: JobFinder
  datasource:
    username: seeker
    password: ${secret.datasource.password}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jobs
  config:
    import: classpath:secret.yaml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    chat:
      client:
        enabled: true
    openai:
      api-key: ${openai.api-key}
      chat:
        options:
          model: gpt-3.5-turbo-1106